version: '3.8'

services:
  app:
    build: .
    depends_on:
      - mysql
      - mongo
    environment:
      PORT: 8080
      #Mongo
      MONGO_DB: pos_qa
      MONGO_USER: cirotex
      MONGO_PASSWORD: prueba
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      MONGO_CONNECTION: mongodb
      # JWT
      SECRET_TOKEN: prueba
      EXPIRE_TOKEN: 24h
      # Nodemailer
      NODEMAILER_HOST: toulouse.com.co
      NODEMAILER_PORT: 465
      NODEMAILER_SECURE: "true"
      NODEMAILER_USER: no-responder@toulouse.com.co
      NODEMAILER_PASSWORD: 4l1vgR%3
      # Amazon AWS
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIA5MNQTDPXCZ3Y225G
      AWS_SECRET_ACCESS_KEY: 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
      AWS_PUBLIC_BUCKET_NAME: admin-z1bt76x1jqpz961o43xt3ik7pzhd6use1a-s3alias
      # Interapidisimo
      INTER_API: https://stgwww3.interrapidisimo.com
      INTER_SIGNATURE: userManufacturasSTG
      INTER_SECURITY_TOKEN: bearer xn7PLu7KCmgS7uq2D7JkC_44DBN99-vTrXE2BHkh4eTKd7sOzQG5MdqRK74eaRsULyP5z4lkJsQDzyNNZwSJRzHbpESCnQx7L7GTI3ZXswLugl1CrdUbVbXKoE6u07HfZsfRzXEfsVKxQHwUS-khx2m73zpoMb8xwU41GaUTvjxupa_mIQtxzorUyI86cruaPKaSCwPib1uZtdkzHhfG2jqnGIi3OYAIDWGMWAMnzVyigSfmkk6ise76zLmPhAkc
      # Fedex
      FEDEX_API: https://apis-sandbox.fedex.com
      FEDEX_CLIENT_ID: l71770d83ad25a4b3d961c3ed8ab48ec88
      FEDEX_CLIENT_SECRET: dc0838dab7bc4c75be8db1adbead2f20
      FEDEX_ACCOUNT_NUMBER: 740561073
      FEDEX_POSTAL_CODE_DEFAULT: 055413
      FEDEX_COUNTRY_DEFAULT: CO
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn run start:dev

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  mongo:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cirotex
      - MONGO_INITDB_ROOT_PASSWORD=prueba
      - MONGO_INITDB_DATABASE=pos_qa
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

networks:
  default:
    name:  cirotex_network

volumes:
  mongo-data:
