version: '3.8'

services:
  app:
    build: .
    environment:
      PORT: 8080
      #Mongo
      MONGO_DB: cirotex
      MONGO_USER: devCirotex
      MONGO_PASSWORD: 1234
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      MONGO_CONNECTION: mongodb
      MONGO_ATLAS_URI: mongodb+srv://devCirotex:1234@cluster0.totgkft.mongodb.net/cirotex
      # JWT
      SECRET_TOKEN: prueba
      EXPIRE_TOKEN: 24h
      # Nodemailer
      NODEMAILER_HOST: toulouse.com.co
      NODEMAILER_PORT: 465
      NODEMAILER_SECURE: "true"
      NODEMAILER_USER: no-responder@toulouse.com.co
      NODEMAILER_PASSWORD: 4l1vgR%3
      # Amazon AWS
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIA5MNQTDPXCZ3Y225G
      AWS_SECRET_ACCESS_KEY: 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
      AWS_PUBLIC_BUCKET_NAME: admin-z1bt76x1jqpz961o43xt3ik7pzhd6use1a-s3alias
      # Interapidisimo
      INTER_API: https://stgwww3.interrapidisimo.com
      INTER_SIGNATURE: userManufacturasSTG
      INTER_AUTHORIZATION: bearer xn7PLu7KCmgS7uq2D7JkC_44DBN99-vTrXE2BHkh4eTKd7sOzQG5MdqRK74eaRsULyP5z4lkJsQDzyNNZwSJRzHbpESCnQx7L7GTI3ZXswLugl1CrdUbVbXKoE6u07HfZsfRzXEfsVKxQHwUS-khx2m73zpoMb8xwU41GaUTvjxupa_mIQtxzorUyI86cruaPKaSCwPib1uZtdkzHhfG2jqnGIi3OYAIDWGMWAMnzVyigSfmkk6ise76zLmPhAkc
      INTER_CITY_DEFAULT: "05360000"
      INTER_CLIENT_ID: 4281
      # Fedex
      FEDEX_API: https://apis-sandbox.fedex.com
      FEDEX_CLIENT_ID: l71770d83ad25a4b3d961c3ed8ab48ec88
      FEDEX_CLIENT_SECRET: dc0838dab7bc4c75be8db1adbead2f20
      FEDEX_ACCOUNT_NUMBER: 740561073
      FEDEX_POSTAL_CODE_DEFAULT: "055411"
      FEDEX_COUNTRY_DEFAULT: CO
      # DATOS EXTRA
      API_URL: https://qa.t0n53eq7nj176.us-east-1.cs.amazonlightsail.com
      API_WEB: https://wholesalers.toulouse.com.co

    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn run start:dev