version: '3.8'

services:
  app:
    build: .
    depends_on:
      - mysql
      - mongodb
    environment:
      PORT: 8080
      MONGO_DB: pos_qa
      MONGO_USER: cirotex
      MONGO_PASSWORD: prueba
      MONGO_PORT: 27017
      MONGO_HOST: mongodb
      MONGO_CONNECTION: mongodb
      MARIADB_DB: pos_qa
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
      MARIADB_PORT: 3306
      MARIADB_HOST: mysql
      SECRET_TOKEN: prueba
      EXPIRE_TOKEN: 24h
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn run start:dev

  mysql:
    image: mysql:5
    environment:
     - MYSQL_DATABASE=pos_qa
     - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cirotex
      - MONGO_INITDB_ROOT_PASSWORD=prueba
      - MONGO_INITDB_DATABASE=pos_qa
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

networks:
  default:
    name:  cirotex_network

volumes:
  mongo-data:
