import { applyDecorators, SetMetadata, UseGuards } from '@nestjs/common';
import { JwtAuthGuard } from '../guards/jwt-auth.guard';
import { PermissionsGuard } from '../guards/permissions.guard';

export enum InventoryPermissions {
	ACCESS_ERP = 'ACCESS_ERP',
	ACCESS_INVENTORY = 'ACCESS_INVENTORY',
	ACCESS_INVENTORY_ADJUSTMENTS = 'ACCESS_INVENTORY_ADJUSTMENTS',
	ACCESS_INVENTORY_CONFIGURATIONS = 'ACCESS_INVENTORY_CONFIGURATIONS',
	ACCESS_INVENTORY_INPUTS = 'ACCESS_INVENTORY_INPUTS',
	ACCESS_INVENTORY_OUTPUTS = 'ACCESS_INVENTORY_OUTPUTS',
	ACCESS_INVENTORY_REQUESTS = 'ACCESS_INVENTORY_REQUESTS',
	ACCESS_INVENTORY_TRANSFER = 'ACCESS_INVENTORY_TRANSFER',
	READ_INVENTORY_INPUTS = 'READ_INVENTORY_INPUTS',
	READ_INVENTORY_ADJUSTMENTS = 'READ_INVENTORY_ADJUSTMENTS',
	READ_INVENTORY_OUTPUTS = 'READ_INVENTORY_OUTPUTS',
	READ_INVENTORY_REQUESTS = 'READ_INVENTORY_REQUESTS',
	READ_INVENTORY_TRANSFERS = 'READ_INVENTORY_TRANSFERS',
	READ_INVENTORY_ATTRIBS = 'READ_INVENTORY_ATTRIBS',
	READ_INVENTORY_BRANDS = 'READ_INVENTORY_BRANDS',
	READ_INVENTORY_CATEGORIES = 'READ_INVENTORY_CATEGORIES',
	READ_INVENTORY_COLORS = 'READ_INVENTORY_COLORS',
	READ_INVENTORY_REFERENCES = 'READ_INVENTORY_REFERENCES',
	READ_INVENTORY_SIZES = 'READ_INVENTORY_SIZES',
	CREATE_INVENTORY_ADJUSTMENT = 'CREATE_INVENTORY_ADJUSTMENT',
	CREATE_INVENTORY_INPUT = 'CREATE_INVENTORY_INPUT',
	CREATE_INVENTORY_OUTPUT = 'CREATE_INVENTORY_OUTPUT',
	CREATE_INVENTORY_REQUEST = 'CREATE_INVENTORY_REQUEST',
	CREATE_INVENTORY_TRANSFER = 'CREATE_INVENTORY_TRANSFER',
	CREATE_INVENTORY_ATTRIB = 'CREATE_INVENTORY_ATTRIB',
	CREATE_INVENTORY_BRAND = 'CREATE_INVENTORY_BRAND',
	CREATE_INVENTORY_CATEGORY = 'CREATE_INVENTORY_CATEGORY',
	CREATE_INVENTORY_COLOR = 'CREATE_INVENTORY_COLOR',
	CREATE_INVENTORY_REFERENCE = 'CREATE_INVENTORY_REFERENCE',
	CREATE_INVENTORY_PRODUCT = 'CREATE_INVENTORY_PRODUCT',
	CREATE_INVENTORY_SIZE = 'CREATE_INVENTORY_SIZE',
	UPDATE_INVENTORY_ADJUSTMENT = 'UPDATE_INVENTORY_ADJUSTMENT',
	UPDATE_INVENTORY_INPUT = 'UPDATE_INVENTORY_INPUT',
	UPDATE_INVENTORY_OUTPUT = 'UPDATE_INVENTORY_OUTPUT',
	UPDATE_INVENTORY_REQUEST = 'UPDATE_INVENTORY_REQUEST',
	UPDATE_INVENTORY_TRANSFER = 'UPDATE_INVENTORY_TRANSFER',
	UPDATE_INVENTORY_ATTRIB = 'UPDATE_INVENTORY_ATTRIB',
	UPDATE_INVENTORY_BRAND = 'UPDATE_INVENTORY_BRAND',
	UPDATE_INVENTORY_CATEGORY = 'UPDATE_INVENTORY_CATEGORY',
	UPDATE_INVENTORY_COLOR = 'UPDATE_INVENTORY_COLOR',
	UPDATE_INVENTORY_REFERENCE = 'UPDATE_INVENTORY_REFERENCE',
	UPDATE_INVENTORY_PRODUCT = 'UPDATE_INVENTORY_PRODUCT',
	UPDATE_INVENTORY_SIZE = 'UPDATE_INVENTORY_SIZE',
	AUTOGENERATE_INVENTORY_REQUEST = 'AUTOGENERATE_INVENTORY_REQUEST',
	CONFIRM_INVENTORY_TRANSFER = 'CONFIRM_INVENTORY_TRANSFER',
}

export const PERMISSIONS_KEY = 'permissions';
export const RequirePermissions = (...permissions: [InventoryPermissions]) =>
	applyDecorators(
		UseGuards(JwtAuthGuard, PermissionsGuard),
		SetMetadata(PERMISSIONS_KEY, permissions),
	);
